### ISSUE TITLE
Copy out of results is empty

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-ui#238]
The top level copy button that copies the entire set to clipboard does not appear to work, but copies the following text
```
[

]
```
<img width="856" alt="Screenshot 2023-08-22 at 5 20 44 PM" src="https://github.com/edgedb/edgedb-ui/assets/6811459/454a6fc8-7123-4541-9760-066252f26a8f">

<img width="301" alt="Screenshot 2023-08-22 at 5 20 50 PM" src="https://github.com/edgedb/edgedb-ui/assets/6811459/a8a84cac-3188-445a-a2da-9d5a906bac12">

**Comment by jackfischer** [comment]
Seemingly fixed in 3.3.

**Comment by jackfischer** [comment]
It _sometimes_ works. On some results the data is copied out correctly and on others it is not. Currently don't have an obvious differentiator

**Comment by jackfischer** [comment]
No console errors when this occurs

**Comment by janwirth** [comment]
This is STILL not working, running edgeDB 5.6, implicit limit OFF
